#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidWakeMeUp.Resource", IsApplication=true)]

namespace AndroidWakeMeUp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::AndroidWakeMeUp.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::AndroidWakeMeUp.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::AndroidWakeMeUp.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::AndroidWakeMeUp.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::AndroidWakeMeUp.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::AndroidWakeMeUp.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::AndroidWakeMeUp.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::AndroidWakeMeUp.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::AndroidWakeMeUp.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::AndroidWakeMeUp.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::AndroidWakeMeUp.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::AndroidWakeMeUp.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::AndroidWakeMeUp.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::AndroidWakeMeUp.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::AndroidWakeMeUp.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::AndroidWakeMeUp.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::AndroidWakeMeUp.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::AndroidWakeMeUp.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::AndroidWakeMeUp.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::AndroidWakeMeUp.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::AndroidWakeMeUp.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::AndroidWakeMeUp.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::AndroidWakeMeUp.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int fab_colorDisabled = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int fab_colorNormal = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int fab_colorPressed = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fab_colorRipple = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fab_shadow = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fab_size = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int accent = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int fab_material_blue_500 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primary = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int primary_dark = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int fab_elevation_lollipop = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int fab_scroll_threshold = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int fab_shadow_size = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int fab_size_mini = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int fab_size_normal = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000a
			public const int activityList = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int current_city_name = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int current_date_info = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int current_temp_info = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int current_time_am_pm_info = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int current_time_info = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int current_weather_img = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int current_weather_info = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int mini = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int normal = 2131230721;
			
			// aapt resource value: 0x7f08000d
			public const int toolbar = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int topbar = 2131230722;
			
			// aapt resource value: 0x7f08000b
			public const int txtTime = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int txtTitle = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TimeItemLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Toolbar = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
